version: '3'

services:
  web:
    build:             #buildから実施
        context: ./web
    ports:             #-p ポートフォワーディング
      - '8080:8080'
    volumes:           #-v hostディレクトリ(./web)をコンテナディレクトリ(/workspace)にマウント
      - ./web:/workspace/web
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/web/target
    tty: true          #-t ttyを割り当てます。
    stdin_open: true   #-i STDINを開きます。
    command: /bin/sh -c "cargo watch -x run"

volumes:
  cargo-cache:
  target-cache: