FROM rust:latest

# Rust first install Only
# Because cargo's Execution result were written Cargo.toml.
# Updated Cargo.toml will be generated in your local environment.
# RUN cargo install cargo-edit

# RUN cd /workspaces/ && \
#      cargo new smart_dog --bin && \
#      cd /workspaces/smart_dog/ && \
#      cargo add actix-web actix-rt
