FROM rust:latest

# Rust first install Only
# Because cargo's Execution result were written Cargo.toml.
# Updated Cargo.toml will be generated in your local environment.
# RUN cargo install cargo-edit

# RUN cd /workspace/ && \
#     cargo new web --bin

# RUN cd /workspace/web && \
#     cargo add actix-web actix-rt && \
#     cargo add thiserror && \
#     cargo add r2d2 r2d2_sqlite && \
#     cargo add askama
